### ISSUE TITLE
Java 8 code clean up [DATAKV-160]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#138]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAKV-160](https://jira.spring.io/browse/DATAKV-160?redirect=false)** and commented

make use of Java 8 language features.
eg. use streaming API in the `Map` repository implementation and filters

---
No further details from [DATAKV-160](https://jira.spring.io/browse/DATAKV-160?redirect=false)

**Comment by jxblum** [comment]
Spring Data KeyValue is now based on Java 17 and the entire codebase could be reviewed and refactored to better leverage Java 17 features.
