### ISSUE TITLE
Add support for unique fields [DATAKV-252]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#229]
**[jpomykala](https://jira.spring.io/secure/ViewProfile.jspa?name=jpomykala1)** opened **[DATAKV-252](https://jira.spring.io/browse/DATAKV-252?redirect=false)** and commented

I think it would be great to have an option to set custom fields as unique like in regular NoSQL & RDBMS

---
No further details from [DATAKV-252](https://jira.spring.io/browse/DATAKV-252?redirect=false)

**Comment by jxblum** [comment]
The implementation of uniqueness in different data structures and underlying data stores is quite complex and different, or "unique".  Spring Data KeyValue is a general abstraction, and while it might make sense to define a "general" concept of uniqueness, implementation-wise, this will very much be up to the individual stores.

Additionally, there has not been any additional requests/votes for such a feature, therefore, closing this ticket.
