### ISSUE TITLE
Update CI jobs for Java 15 [DATAKV-320]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#298]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAKV-320](https://jira.spring.io/browse/DATAKV-320?redirect=false)** and commented

---
No further details from [DATAKV-320](https://jira.spring.io/browse/DATAKV-320?redirect=false)

**Comment by jxblum** [comment]
We now [build on Java 17](https://github.com/spring-projects/spring-data-keyvalue/blob/main/ci/pipeline.properties#L2) in Spring Data (KeyVaue) `3.0`.
