### ISSUE TITLE
Update CI jobs with Docker Login [DATAKV-333]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#311]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAKV-333](https://jira.spring.io/browse/DATAKV-333?redirect=false)** and commented

---
No further details from [DATAKV-333](https://jira.spring.io/browse/DATAKV-333?redirect=false)

**Comment by jxblum** [comment]
This is no longer applicable since we are [using](https://github.com/spring-projects/spring-data-keyvalue/blob/main/ci/pipeline.properties#L6-L7) VMware's Harbor Proxy for Docker Hub.
