### ISSUE TITLE
Update reference documentation with examples that match `@EnableMapRepositories`

### ISSUE THREAD

**Issue by sdavids** [spring-projects/spring-data-keyvalue#358]
https://docs.spring.io/spring-data/keyvalue/docs/current/reference/html/#key-value.template-configuration

Add/modify https://github.com/spring-projects/spring-data-examples/blob/master/map/src/test/java/example/springdata/map/PersonRepositoryIntegrationTest.java :

```
@RunWith(SpringRunner.class)
@SpringBootTest
public class PersonRepositoryIntegrationTest {

  static final class MapKeyValueAdapterExt extends MapKeyValueAdapter {

    MapKeyValueAdapterExt(Class<? extends Map> mapType) {
      super(mapType);
    }

    @Override
    public Object get(Object id, String keyspace) {
      System.out.println(keyspace + ":" + id);
      return super.get(id, keyspace);
    }
  }

  @SpringBootApplication
  @EnableMapRepositories
  static class Config {

    @Bean
    public KeyValueOperations keyValueTemplate() {
      return new KeyValueTemplate(keyValueAdapter());
    }

    @Bean
    public KeyValueAdapter keyValueAdapter() {
      return new MapKeyValueAdapterExt(ConcurrentHashMap.class);
    }
  }

// ...

}
```

`MapKeyValueAdapterExt#get(Object, String)` will not be called.

**Comment by mp911de** [comment]
The default bean name is `mapKeyValueTemplate`. Please either rename your `@Bean` method or specify the bean name via `@EnableMapRepositories(keyValueTemplateRef=…)`.

**Comment by sdavids** [comment]
Maybe update the doc?

**Comment by mp911de** [comment]
It's already documented via Javadoc on the `@EnableMapRepositories` annotation.

**Comment by sdavids** [comment]
Sorry for the conciseness above ...

https://docs.spring.io/spring-data/keyvalue/docs/current/reference/html/#key-value.template-configuration

contains a section on how to "use a different type or preinitialize the adapter".

If we add/modify https://github.com/spring-projects/spring-data-examples/blob/master/map/src/test/java/example/springdata/map/PersonRepositoryIntegrationTest.java by copy and pasting the example from https://docs.spring.io/spring-data/keyvalue/docs/current/reference/html/#key-value.template-configuration we get the following:

```
@RunWith(SpringRunner.class)
@SpringBootTest
public class PersonRepositoryIntegrationTest {

  static final class MapKeyValueAdapterExt extends MapKeyValueAdapter {

    MapKeyValueAdapterExt(Class<? extends Map> mapType) {
      super(mapType);
    }

    @Override
    public Object get(Object id, String keyspace) {
      System.out.println(keyspace + ":" + id);
      return super.get(id, keyspace);
    }
  }

  @SpringBootApplication
  @EnableMapRepositories
  static class Config {

    @Bean
    public KeyValueOperations keyValueTemplate() {
      return new KeyValueTemplate(keyValueAdapter());
    }

    @Bean
    public KeyValueAdapter keyValueAdapter() {
      return new MapKeyValueAdapterExt(ConcurrentHashMap.class);
    }
  }

// ...

}
```

Running the test we will experience that `MapKeyValueAdapterExt#get(Object, String)` will not be called.

Either the implementation does not work or the documentation contains an example that does dot work.

---

Maybe update the documentation https://docs.spring.io/spring-data/keyvalue/docs/current/reference/html/#key-value.template-configuration so that the example shown does work out of the box when copy and pasted?

**Comment by mp911de** [comment]
Agreed, updating the docs to reduce name confusion makes sense.
