### ISSUE TITLE
Custom QueryEngine limitation with custom SORT type

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-data-keyvalue#410]
Some time ago I experimented a bit with the custom `QueryEngine` implementation in combination with the `KeyValueOperations`/`KeyValueQuery`.

`QueryEngine` has the following characteristics: `QueryEngine<ADAPTER extends KeyValueAdapter, CRITERIA, SORT>`.
So it supports providing custom types for both CRITERIA and SORT instead of the default SpEL implementation.

`KeyValueOperations` has:
`<T> Iterable<T> find(KeyValueQuery<?> query, Class<T> type);`

but `KeyValueQuery` unfortunately looks like `KeyValueQuery<T>` (and not like `KeyValueQuery<CRITERIA, SORT>`) and hence has:

`public KeyValueQuery(@Nullable T criteria, Sort sort) { .. }`

this only allow a custom `CRITERIA` type but not a custom `SORT` type..

Is there a reason for this?

This way having a custom SORT type in `QueryEngine` doesn't make sense as we cannot pass it via `KeyValueQuery`/`KeyValueOperations`.

**Comment by mp911de** [comment]
There are a few things that seem similar but resolve to slightly different types:

* `<T>` of `KeyValueQuery`: This is the criteria type, such as an `SpelExpression`. It matches the `CRITERIA` type in `QueryEngine`
* `<CRITERIA>` in `QueryEngine`: The criteria is being resolved by a `CriteriaAccessor` from a `KeyValueQuery<?>`.
* `<SORT>` in `QueryEngine`: This is the actual object that performs sorting, such as a `Comparator`. A `SortAccessor` resolves `<SORT>` from `KeyValueQuery<?>`.

The reason criteria are interchangeable while sort is not, is that we have a single representation `org.springframework.data.domain.Sort` in Spring Data that is used to specify the sort order. Note that `Sort` is the specification of the order while `<SORT>` implements the sorting. Stores that can natively sort data, can put a placeholder type into `<SORT>` and simply not care about it.

**Comment by marceloverdijk** [comment]
Thanks Mark for the explanation. 

I fully understand your point about the single representation (`org.springframework.data.domain.Sort`) in Spring Data and it not being interchangeable.

I'm trying to use a Map based key value store with filtering (`Predicate`) and sorting (`Comparator`) but without SpEL involved.
Reason is I'm - and maybe unfairly - a bit worried of performance drop vs non-SpEL approach.

I don't mind providing a custom Repository interface/implementation (extending `CrudRepository`) with e.g.:
- `List<T> findAll(Comparator sort)`
- `List<T> findAll(Predicate<T> criteria, Comparator<T> sort)`

(this as alternative to `PagingAndSortingRepository`)

**Comment by mp911de** [comment]
If you want to provide a `Comparator` externally, then the only way to do so is by subclassing `Sort` (see `QSort`) and it might be not sufficient. `KeyValueQuery.orderBy` conditionally concatenates sort objects `Sort.and(Sort)`. SpEL (without compilation) resorts to reflection which imposes a bit of performance drag.

**Comment by marceloverdijk** [comment]
Yes, actually I was also looking in `Sort.TypedSort` and noticed that probably bc of the concatenation I ended up with a "normal" `Sort` instead.
But looking at the `KeyValueQuery` code now I think it will simply replace the internal sort var if it is unsorted (so not doing the `Sort.and(Sort)`, maybe somewhere else down the line something similar happens...

Could setting `spring.expression.compiler.mode` to either `IMMEDIATE` or `MIXED` maybe help as alternative?
I read there are some compiler limitations but don't know if these limitations apply for criteria and/or sort.

**Comment by mp911de** [comment]
These modes would help with performance. Keep in mind that SpEL compilation uses the object type it sees during evaluation and compiles against that one. If you run into issues please let us know. 

As this ticket isn't actionable any further, I'm closing it. Happy to reopen if there's something we can do.
