### ISSUE TITLE
Spring Support for HBase [DATAKV-2]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#54]
**[Vaibhav Puranik](https://jira.spring.io/secure/ViewProfile.jspa?name=vpuranik)** opened **[DATAKV-2](https://jira.spring.io/browse/DATAKV-2?redirect=false)** and commented

I had created this issue a while ago :

https://jira.springframework.org/browse/SPR-5950

Is it possible for you to move this issue to DATAKV project?

---

**Attachments:**
- [HBaseConfigurationFactoryBean.java](https://jira.spring.io/secure/attachment/18849/HBaseConfigurationFactoryBean.java) (_1.55 kB_)
- [HBaseTemplate.java](https://jira.spring.io/secure/attachment/18850/HBaseTemplate.java) (_2.20 kB_)
- [RowCallback.java](https://jira.spring.io/secure/attachment/18851/RowCallback.java) (_602 bytes_)
- [TableCallback.java](https://jira.spring.io/secure/attachment/18852/TableCallback.java) (_614 bytes_)

**Comment by jxblum** [comment]
Closing as this ticket is really old.
