### ISSUE TITLE
Introduce general 'KeyValueOperations' to enable some portability across different key value databases/blob stores. [DATAKV-31]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#58]
**[Mark Pollack](https://jira.spring.io/secure/ViewProfile.jspa?name=mark.pollack)** opened **[DATAKV-31](https://jira.spring.io/browse/DATAKV-31?redirect=false)** and commented

---

**Affects:** 1.0.0.M1

**Reference URL:** http://forum.springsource.org/showthread.php?p=341514

2 votes, 1 watchers

**Comment by jxblum** [comment]
Already implemented ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/main/src/main/java/org/springframework/data/keyvalue/core/KeyValueOperations.java); [Javadoc](https://javadoc.io/doc/org.springframework.data/spring-data-keyvalue/latest/org/springframework/data/keyvalue/core/KeyValueOperations.html)).
