### ISSUE TITLE
Question: get ValueComparingPredicate information. 

### ISSUE THREAD

**Issue by salaboy** [spring-projects/spring-data-keyvalue#584]
I am looking at providing a new implementation for the KeyValueAdapter to support another provider. However, when doing this and extending Repositories with, for example, the `findByX(String x)` method, this creates a Query containing a Criteria that uses the `PredicateQueryCreator.ValueComparingPredicate` type of object that is package-scoped. From outside the internals of spring data, I cannot get the information from this query predicate. 

I wonder if this is on purpose and if I should create a new way of making these Query Criteria for my implementation. For my implementation, it will be enough to get the `path` and the `check` from the `PredicateQueryCreator.ValueComparingPredicate`, but as far as I can see, that is not something I can access.

Folks @odrotbohm or @christophstrobl can you provide some pointers?

**Comment by christophstrobl** [comment]
Thank you for reaching out. I'm not sure I fully understand what you want to archive. Maybe you can provide a [sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that gives a bit more context.
In case you think about building a new query engine, you may want to have a look at [spring-data-hazelcast](https://github.com/hazelcast/spring-data-hazelcast/).

**Comment by salaboy** [comment]
@christophstrobl thanks for reaching out.. After more investigation, I found out that my question was totally wrong. My gut tells me that I don't need a full new engine, but just a new `QueryCreator`, as I want to reuse all the mechanisms that Spring Data uses to create the queries, but the output of those queries shouldn't be functions, just SQL strings. It sounds like JPA would be doing something like that. I will check `spring-data-hazelcast` too. 

Thanks a lot for the pointers.
