### ISSUE TITLE
Support for additional Part Types

### ISSUE THREAD

**Issue by TomVanWemmel** [spring-projects/spring-data-keyvalue#603]
I noticed that there is no support for negating keywords and wondered if there is a particular reason for this. 

Is it possible to add support for the following types to [PredicateQueryCreator](https://github.com/spring-projects/spring-data-keyvalue/blob/main/src/main/java/org/springframework/data/keyvalue/repository/query/PredicateQueryCreator.java)?
- NOT_IN
- NOT_LIKE
- NEGATING_SIMPLE_PROPERTY

I'm willing to work on a PR if I can get some pointers what needs to change.

**Comment by TomVanWemmel** [comment]
It looked like a simple modification, so I took the liberty to implement it right away.

**Comment by TomVanWemmel** [comment]
@mp911de Is there anything I can do to progress this issue?

**Comment by mp911de** [comment]
It's us who is the bottleneck as we're busy with releases and bugfixes for the time being. We have your PR on the radar and will come back to it for the 3.5 release.

**Comment by mp911de** [comment]
I had a bit of spare time left today (right before taking some time off during the holidays) and merged your PR. Thanks a lot.
